package agent

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// Agent represents an agent definition stored as a JSONB document.
// Only the fields required for database-level operations (lookup key, change
// detection, audit timestamps) are top-level columns. Everything else lives
// inside the Definition JSONB document.
type Agent struct {
	// ID is the UUID primary key, generated by the database on INSERT.
	ID uuid.UUID `db:"id"`

	// Name is the unique lookup key (lowercase-with-hyphens format).
	Name string `db:"name"`

	// Definition is the complete agent specification as a JSONB document.
	// The application marshals and unmarshals this field; the database stores
	// it as a single JSONB column.
	Definition json.RawMessage `db:"definition"`

	// CRC64 is the CRC-64 checksum of the serialized definition for change
	// detection. Stored as a decimal string representation of a uint64.
	CRC64 string `db:"crc64"`

	// CreatedAt is set by the database DEFAULT on INSERT.
	CreatedAt time.Time `db:"created_at"`

	// UpdatedAt is set by the application on every UPDATE.
	UpdatedAt time.Time `db:"updated_at"`
}

// ManifestEntry represents a single entity in the sync manifest.
// Used by the sync protocol to compare local and remote CRC64 values.
type ManifestEntry struct {
	Name  string `db:"name"`
	CRC64 string `db:"crc64"`
}
