package skillfile

import (
	"time"

	"github.com/google/uuid"
)

// SkillFile represents a child file for a skill definition.
// Skill files are keyed by the composite (skill_id, path) pair. Unlike agents
// and skills, they do not use the JSONB document model; content is stored
// directly in a TEXT column.
type SkillFile struct {
	// ID is the UUID primary key, generated by the database on INSERT.
	ID uuid.UUID `db:"id"`

	// SkillID references the parent skill (CASCADE DELETE).
	SkillID uuid.UUID `db:"skill_id"`

	// Path is the file path within the skill directory.
	Path string `db:"path"`

	// Content is the file content stored as TEXT.
	Content string `db:"content"`

	// CRC64 is the CRC-64 checksum of the content for change detection.
	// Stored as a decimal string representation of a uint64.
	CRC64 string `db:"crc64"`

	// CreatedAt is set by the database DEFAULT on INSERT.
	CreatedAt time.Time `db:"created_at"`

	// UpdatedAt is set by the application on every UPDATE.
	UpdatedAt time.Time `db:"updated_at"`
}

// ManifestEntry represents a single file in the skill file manifest.
// Used by the sync protocol to compare local and remote CRC64 values.
type ManifestEntry struct {
	Path  string `db:"path"`
	CRC64 string `db:"crc64"`
}
