vocabulary:
  languages:
    - agnostic
    - c
    - cpp
    - csharp
    - cql
    - cypher
    - dart
    - delphi
    - elixir
    - erlang
    - go
    - java
    - javascript
    - kotlin
    - lua
    - matlab
    - mql
    - objective-c
    - perl
    - php
    - plsql
    - powershell
    - python
    - r
    - ruby
    - rust
    - scala
    - shell
    - sql
    - swift
    - tsql
    - typescript
    - visual-basic
  domains:
    - api-design
    - backend
    - frontend
    - testing
    - devops
    - cli
    - data-design
    - documentation
