name: Mnemonic Application CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'src/mnemonic/internal/**'
      - 'src/mnemonic/cmd/**'
      - 'src/mnemonic/go.mod'
      - 'src/mnemonic/go.sum'
      - 'src/mnemonic/build/**'
      - '.github/workflows/mnemonic-app-ci.yaml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'src/mnemonic/internal/**'
      - 'src/mnemonic/cmd/**'
      - 'src/mnemonic/go.mod'
      - 'src/mnemonic/go.sum'
      - 'src/mnemonic/build/**'
      - '.github/workflows/mnemonic-app-ci.yaml'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: src/mnemonic

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run build script
        run: ./build/build.sh
